export const MY_VEHICLE_MODELS: Record<string, string[]> = {
  'Perodua':        ['Axia', 'Bezza', 'Myvi', 'Ativa', 'Aruz', 'Alza', 'Kancil', 'Kelisa', 'Kenari', 'Viva'],
  'Proton':         ['Saga', 'Persona', 'Iriz', 'Exora', 'X50', 'X70', 'X90', 'S70', 'X80', 'A70', 'Perdana', 'Preve', 'Suprima S'],
  'Toyota':         ['Vios', 'Yaris', 'Corolla', 'Corolla Cross', 'Camry', 'C-HR', 'RAV4', 'Fortuner', 'Hilux', 'Alphard', 'Vellfire', 'HiAce', 'Veloz', 'Avanza', 'Rush', 'Land Cruiser', 'Land Cruiser Prado', 'GR86', 'Supra', 'bZ4X'],
  'Honda':          ['City', 'City Hatchback', 'Jazz', 'HR-V', 'CR-V', 'Accord', 'Civic', 'BR-V', 'WR-V', 'Odyssey', 'e:N1'],
  'Nissan':         ['Almera', 'Kicks', 'X-Trail', 'Navara', 'Serena', 'Note', 'Leaf', 'Magnite', 'Sylphy'],
  'Mitsubishi':     ['Attrage', 'ASX', 'Eclipse Cross', 'Outlander', 'Triton', 'Xpander', 'Pajero Sport', 'Galant'],
  'Mazda':          ['Mazda2', 'Mazda3', 'Mazda6', 'CX-3', 'CX-30', 'CX-5', 'CX-8', 'CX-60', 'BT-50', 'MX-5'],
  'Suzuki':         ['Swift', 'Ertiga', 'Jimny', 'S-Presso', 'Ignis', 'Vitara', 'Grand Vitara', 'Ciaz', 'APV'],
  'Subaru':         ['XV', 'Forester', 'Outback', 'Legacy', 'WRX', 'BRZ', 'Crosstrek', 'Solterra'],
  'Daihatsu':       ['Terios', 'Gran Max'],
  'Isuzu':          ['D-Max', 'MU-X'],
  'Hyundai':        ['Elantra', 'Tucson', 'Kona', 'Santa Fe', 'Creta', 'Ioniq 5', 'Ioniq 6', 'Venue', 'Stargazer', 'Staria'],
  'Kia':            ['Carnival', 'Sorento', 'Sportage', 'Seltos', 'Cerato', 'Picanto', 'Stinger', 'EV6', 'Niro', 'EV9'],
  'BMW':            ['1 Series', '2 Series', '3 Series', '4 Series', '5 Series', '7 Series', '8 Series', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X7', 'Z4', 'M2', 'M3', 'M4', 'M5', 'iX1', 'iX3', 'iX', 'i4', 'i7'],
  'Mercedes-Benz':  ['A-Class', 'C-Class', 'E-Class', 'S-Class', 'GLA', 'GLB', 'GLC', 'GLE', 'GLS', 'CLA', 'CLS', 'EQA', 'EQB', 'EQC', 'EQE', 'EQS', 'AMG GT', 'G-Class'],
  'Audi':           ['A1', 'A3', 'A4', 'A5', 'A6', 'A7', 'A8', 'Q2', 'Q3', 'Q5', 'Q7', 'Q8', 'e-tron', 'e-tron GT', 'RS3', 'RS5', 'RS7', 'TT'],
  'Volkswagen':     ['Polo', 'Golf', 'Passat', 'Arteon', 'Tiguan', 'T-Cross', 'T-Roc', 'Touareg', 'ID.4'],
  'Porsche':        ['911', 'Cayenne', 'Macan', 'Panamera', 'Taycan', '718 Cayman', '718 Boxster'],
  'Volvo':          ['S60', 'S90', 'V60', 'XC40', 'XC60', 'XC90', 'C40 Recharge', 'EX30', 'EX90'],
  'Land Rover':     ['Defender', 'Discovery', 'Discovery Sport', 'Range Rover', 'Range Rover Sport', 'Range Rover Evoque', 'Range Rover Velar'],
  'Jaguar':         ['XE', 'XF', 'XJ', 'E-Pace', 'F-Pace', 'I-Pace', 'F-Type'],
  'MINI':           ['Cooper', 'Countryman', 'Clubman', 'Convertible', 'Aceman'],
  'Peugeot':        ['208', '308', '408', '2008', '3008', '5008'],
  'Renault':        ['Clio', 'Megane', 'Koleos', 'Captur', 'Kangoo'],
  'Ford':           ['Ranger', 'Everest', 'Bronco', 'Mustang', 'Maverick', 'Transit'],
  'Chevrolet':      ['Colorado', 'Trailblazer', 'Cruze', 'Captiva'],
  'Jeep':           ['Wrangler', 'Cherokee', 'Grand Cherokee', 'Compass', 'Renegade', 'Gladiator'],
  'Tesla':          ['Model 3', 'Model Y', 'Model S', 'Model X', 'Cybertruck'],
  'BYD':            ['Atto 3', 'Seal', 'Dolphin', 'Tang', 'Han', 'Seagull', 'Sea Lion 6', 'Sea Lion 7'],
  'Chery':          ['Omoda 5', 'Omoda C5', 'Tiggo 5x', 'Tiggo 7', 'Tiggo 8'],
  'MG':             ['ZS', 'HS', 'RX5', '5', 'EP', 'VS'],
  'Geely':          ['Coolray', 'Okavango', 'Boyue', 'Emgrand'],
  'Haval':          ['H6', 'Jolion', 'H2'],
  'GWM':            ['Ora Good Cat', 'Tank 300', 'Pickup'],
};
